# Generated by Django 5.0.8 on 2024-08-08 05:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DonateClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=56)),
                ("email", models.EmailField(max_length=254)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date_payment", models.DateField(auto_now_add=True)),
                ("status", models.TextField(blank=True, default="N/A")),
                (
                    "invoice_id",
                    models.CharField(blank=True, default="", max_length=128),
                ),
            ],
        ),
    ]
